AlignParameters:
  Enabled: false
ClassLength:
  CountComments: false
  Max: 200
Documentation:
  Enabled: false
LineLength:
  Max: 120
MethodLength:
  CountComments: false
  Max: 15
Metrics/AbcSize:
 Max: 25
Metrics/BlockLength:
  Exclude:
    - 'app/api/**/*'
    - 'spec/**/*'

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'tmp/**/*'
    - 'script/**/*'
    - 'Gemfile'
    - 'Guardfile'
    - 'Capfile'
    - 'Rakefile'

Style/MultilineOperationIndentation:
  EnforcedStyle: indented
  SupportedStyles:
    - aligned
    - indented
Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/DotPosition:
  EnforcedStyle: leading
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
