default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: pmag_development

test:
  <<: *default
  database: pmag_test

production:
  <<: *default
  database: pmag_production
  username: pmag
  password: <%= ENV['PMAG_DATABASE_PASSWORD'] %>
